import { contracts } from 'shared/client';

export const single = contracts.SPLTokenFullResponse;

// object({
//   id: number(),
//   created_by: object({
//     user_id: number(),
//     user_nickname: string(),
//     user_photo_hash: string(),
//   }),
//   name: string(),
//   symbol: string(),
//   description: string(),
//   photo_hash: string(),
//   twitter: string(),
//   telegram: string(),
//   youtube: string().or(z.null()),
//   website: string().or(z.null()),
//   address: string(),
//   trade_started: boolean(),
//   trade_finished: boolean(),
//   last_tx_timestamp: number(),
//   holders: number(),
//   messages: number(),
//   alltime_buy_txes: number(),
//   alltime_sell_txes: number(),
//   volume_24h: number(),
//   mcap: number(),
//   rate: number(),
//   creation_date: number(),
//   is_nsfw: boolean(),
//   mcap_diff_24h: number(),
//   is_streaming: boolean(),
//   bounding_curve: number(),
//   is_creator: boolean(),
//   mcap_diff_5m: number(),
//   mcap_diff_1h: number(),
//   mcap_diff_6h: number(),
//   alltime_volume: number(),
//   alltime_buy_volume: number(),
//   alltime_sell_volume: number(),
//   alltime_makers: number(),
//   slug: string().or(z.null()),
//   alltime_buyers: number(),
//   alltime_sellers: number(),
//   virtual_tokens: number(),
//   virtual_sol: number(),
// });
