import { TokenLivestreamProps } from 'entities/token';
import { Market } from '../types';

export const livestreamTokens: TokenLivestreamProps[] = [
  {
    preview: 'https://i.ibb.co/Kpm43kXm/dark-souls-warrior-on-battlefield-desktop-wallpaper-4k.jpg',
    watching: 340,
    comments: 3,
    energy: 100,
    user: '11%',
    cook: '8%',
    circled: '13%',
    mouse: '54%',
    duration: '12m',
    token: {
      logo: 'https://i.ibb.co/vxG3R9QG/arthur-morgan-christmas-celebration-desktop-wallpaper-4k.jpg',
      name: 'SYPER',
      contract: 'compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq',
    },
    users: 8,
    wallets: 13,
    author: 'Andro910',
    capitalization: 2452.13,
    title: 'Umk99ujM',
  },
  {
    preview: 'https://i.ibb.co/Kpm43kXm/dark-souls-warrior-on-battlefield-desktop-wallpaper-4k.jpg',
    watching: 340,
    comments: 3,
    energy: 100,
    user: '11%',
    cook: '8%',
    circled: '13%',
    mouse: '54%',
    duration: '12m',
    token: {
      logo: 'https://i.ibb.co/vxG3R9QG/arthur-morgan-christmas-celebration-desktop-wallpaper-4k.jpg',
      name: 'SYPER',
      contract: 'compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq',
    },
    users: 8,
    wallets: 13,
    author: 'Andro910',
    capitalization: 2452.13,
    title: 'Umk99ujM',
  },
  {
    preview: 'https://i.ibb.co/Kpm43kXm/dark-souls-warrior-on-battlefield-desktop-wallpaper-4k.jpg',
    watching: 340,
    comments: 3,
    energy: 100,
    user: '11%',
    cook: '8%',
    circled: '13%',
    mouse: '54%',
    duration: '12m',
    token: {
      logo: 'https://i.ibb.co/vxG3R9QG/arthur-morgan-christmas-celebration-desktop-wallpaper-4k.jpg',
      name: 'SYPER',
      contract: 'compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq',
    },
    users: 8,
    wallets: 13,
    author: 'Andro910',
    capitalization: 2452.13,
    title: 'Umk99ujM',
  },
  {
    preview: 'https://i.ibb.co/Kpm43kXm/dark-souls-warrior-on-battlefield-desktop-wallpaper-4k.jpg',
    watching: 340,
    comments: 3,
    energy: 100,
    user: '11%',
    cook: '8%',
    circled: '13%',
    mouse: '54%',
    duration: '12m',
    token: {
      logo: 'https://i.ibb.co/vxG3R9QG/arthur-morgan-christmas-celebration-desktop-wallpaper-4k.jpg',
      name: 'SYPER',
      contract: 'compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq',
    },
    users: 8,
    wallets: 13,
    author: 'Andro910',
    capitalization: 2452.13,
    title: 'Umk99ujM',
  },
  {
    preview: 'https://i.ibb.co/Kpm43kXm/dark-souls-warrior-on-battlefield-desktop-wallpaper-4k.jpg',
    watching: 340,
    comments: 3,
    energy: 100,
    user: '11%',
    cook: '8%',
    circled: '13%',
    mouse: '54%',
    duration: '12m',
    token: {
      logo: 'https://i.ibb.co/vxG3R9QG/arthur-morgan-christmas-celebration-desktop-wallpaper-4k.jpg',
      name: 'SYPER',
      contract: 'compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq',
    },
    users: 8,
    wallets: 13,
    author: 'Andro910',
    capitalization: 2452.13,
    title: 'Umk99ujM',
  },
  {
    preview: 'https://i.ibb.co/Kpm43kXm/dark-souls-warrior-on-battlefield-desktop-wallpaper-4k.jpg',
    watching: 340,
    comments: 3,
    energy: 100,
    user: '11%',
    cook: '8%',
    circled: '13%',
    mouse: '54%',
    duration: '12m',
    token: {
      logo: 'https://i.ibb.co/vxG3R9QG/arthur-morgan-christmas-celebration-desktop-wallpaper-4k.jpg',
      name: 'SYPER',
      contract: 'compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq',
    },
    users: 8,
    wallets: 13,
    author: 'Andro910',
    capitalization: 2452.13,
    title: 'Umk99ujM',
  },
  {
    preview: 'https://i.ibb.co/Kpm43kXm/dark-souls-warrior-on-battlefield-desktop-wallpaper-4k.jpg',
    watching: 340,
    comments: 3,
    energy: 100,
    user: '11%',
    cook: '8%',
    circled: '13%',
    mouse: '54%',
    duration: '12m',
    token: {
      logo: 'https://i.ibb.co/vxG3R9QG/arthur-morgan-christmas-celebration-desktop-wallpaper-4k.jpg',
      name: 'SYPER',
      contract: 'compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq',
    },
    users: 8,
    wallets: 13,
    author: 'Andro910',
    capitalization: 2452.13,
    title: 'Umk99ujM',
  },
  {
    preview: 'https://i.ibb.co/Kpm43kXm/dark-souls-warrior-on-battlefield-desktop-wallpaper-4k.jpg',
    watching: 340,
    comments: 3,
    energy: 100,
    user: '11%',
    cook: '8%',
    circled: '13%',
    mouse: '54%',
    duration: '12m',
    token: {
      logo: 'https://i.ibb.co/vxG3R9QG/arthur-morgan-christmas-celebration-desktop-wallpaper-4k.jpg',
      name: 'SYPER',
      contract: 'compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq',
    },
    users: 8,
    wallets: 13,
    author: 'Andro910',
    capitalization: 2452.13,
    title: 'Umk99ujM',
  },
  {
    preview: 'https://i.ibb.co/Kpm43kXm/dark-souls-warrior-on-battlefield-desktop-wallpaper-4k.jpg',
    watching: 340,
    comments: 3,
    energy: 100,
    user: '11%',
    cook: '8%',
    circled: '13%',
    mouse: '54%',
    duration: '12m',
    token: {
      logo: 'https://i.ibb.co/vxG3R9QG/arthur-morgan-christmas-celebration-desktop-wallpaper-4k.jpg',
      name: 'SYPER',
      contract: 'compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq',
    },
    users: 8,
    wallets: 13,
    author: 'Andro910',
    capitalization: 2452.13,
    title: 'Umk99ujM',
  },
];

export const markets: Market[] = [
  {
    name: 'All tokens',
  },
  {
    name: 'Live stream',
    icon: 'dot',
  },
  {
    name: 'Last order',
  },
  {
    name: 'Top gain',
  },
  {
    name: 'MCAP',
  },
  {
    name: 'Raydium',
  },
  {
    name: 'My tokens',
  },
];
